#!/usr/bin/env node
/**
 * Propagates the root .env into mobile/.env — CLIENT-SAFE VARS ONLY.
 *
 * This exists so the secret boundary is enforced by a machine rather than by
 * remembering. Anything not prefixed EXPO_PUBLIC_ is refused, because
 * EXPO_PUBLIC_ vars are inlined into the APK and an APK is readable by anyone
 * who downloads it.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const srcPath = join(root, ".env");
const outPath = join(root, "mobile", ".env");

if (!existsSync(srcPath)) {
  console.error("✖ No .env at repo root. Copy .env.example to .env and fill it in.");
  process.exit(1);
}

const SERVER_ONLY = [
  "SUPABASE_SERVICE_ROLE_KEY",
  "OPENROUTER_API_KEY",
  "YOUTUBE_API_KEY",
  "IGOT_API_KEY",
];

const lines = readFileSync(srcPath, "utf8").split("\n");
const out = [];
const kept = [];
let leaked = null;

for (const line of lines) {
  const t = line.trim();
  if (!t || t.startsWith("#")) continue;
  const eq = t.indexOf("=");
  if (eq === -1) continue;

  const key = t.slice(0, eq).trim();
  const value = t.slice(eq + 1).trim();

  // Hard stop: a server secret that somehow got an EXPO_PUBLIC_ prefix would
  // ship inside the APK. Fail loudly rather than silently leak.
  if (key.startsWith("EXPO_PUBLIC_") && SERVER_ONLY.some((s) => key.includes(s))) {
    leaked = key;
    break;
  }

  if (key.startsWith("EXPO_PUBLIC_")) {
    out.push(`${key}=${value}`);
    kept.push(key);
  }
}

if (leaked) {
  console.error(`\n✖ REFUSING TO SYNC: "${leaked}" would be compiled into the APK.`);
  console.error("  Server secrets must NOT carry the EXPO_PUBLIC_ prefix.");
  console.error("  They belong in Supabase Edge Function secrets instead:");
  console.error("    npm run secrets:push\n");
  process.exit(1);
}

if (!kept.length) {
  console.error("✖ No EXPO_PUBLIC_* vars found in .env — the app will not be able to reach Supabase.");
  process.exit(1);
}

writeFileSync(
  outPath,
  "# AUTO-GENERATED by `npm run env:sync` — do not edit.\n" +
  "# Source of truth is the repo-root .env.\n" +
  "# Client-safe vars ONLY: everything here is compiled into the APK.\n\n" +
  out.join("\n") + "\n",
);

console.log(`✅ Wrote mobile/.env with ${kept.length} client-safe var(s):`);
for (const k of kept) console.log(`   · ${k}`);
console.log("\n   Server secrets stayed behind, as they should.");
